//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ovn2_FlowControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ovn2_FlowControl.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt val: .
        /// </summary>
        internal static string MenuVal {
            get {
                return ResourceManager.GetString("MenuVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv en siffra för att välja funktion..
        /// </summary>
        internal static string Rad1 {
            get {
                return ResourceManager.GetString("Rad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 = Avsluta.
        /// </summary>
        internal static string Rad2 {
            get {
                return ResourceManager.GetString("Rad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 = Ungdom eller pensionär.
        /// </summary>
        internal static string Rad3 {
            get {
                return ResourceManager.GetString("Rad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 = Pris för sällskap.
        /// </summary>
        internal static string Rad4 {
            get {
                return ResourceManager.GetString("Rad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 = Upprepa tio gånger.
        /// </summary>
        internal static string Rad5 {
            get {
                return ResourceManager.GetString("Rad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 = Det tredje ordet.
        /// </summary>
        internal static string Rad6 {
            get {
                return ResourceManager.GetString("Rad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välkommen till huvud menyn!.
        /// </summary>
        internal static string Rubrik {
            get {
                return ResourceManager.GetString("Rubrik", resourceCulture);
            }
        }
    }
}
