//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ovn2_FlowControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ovn2_FlowControl.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange ålder: .
        /// </summary>
        internal static string AngeAlder {
            get {
                return ResourceManager.GetString("AngeAlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange ålder för person .
        /// </summary>
        internal static string AngeAlderForPerson {
            get {
                return ResourceManager.GetString("AngeAlderForPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal personer: .
        /// </summary>
        internal static string AntalPersoner {
            get {
                return ResourceManager.GetString("AntalPersoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det tredje ordet är: .
        /// </summary>
        internal static string DetTredjeOrdet {
            get {
                return ResourceManager.GetString("DetTredjeOrdet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste skriva en mening..
        /// </summary>
        internal static string DuMasteSkriva {
            get {
                return ResourceManager.GetString("DuMasteSkriva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felaktig input, välj 0-4..
        /// </summary>
        internal static string FelaktigInput {
            get {
                return ResourceManager.GetString("FelaktigInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratis.
        /// </summary>
        internal static string Gratis {
            get {
                return ResourceManager.GetString("Gratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hur många personer är ni? .
        /// </summary>
        internal static string HurManga {
            get {
                return ResourceManager.GetString("HurManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv en mening med minst 3 ord: .
        /// </summary>
        internal static string Mening3ord {
            get {
                return ResourceManager.GetString("Mening3ord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mening måste innehålla minst 3 ord..
        /// </summary>
        internal static string MeningMasteInnehalla3ord {
            get {
                return ResourceManager.GetString("MeningMasteInnehalla3ord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv en siffra för att välja funktion..
        /// </summary>
        internal static string MenuRad1 {
            get {
                return ResourceManager.GetString("MenuRad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 = Avsluta.
        /// </summary>
        internal static string MenuRad2 {
            get {
                return ResourceManager.GetString("MenuRad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 = Ungdom eller pensionär.
        /// </summary>
        internal static string MenuRad3 {
            get {
                return ResourceManager.GetString("MenuRad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 = Pris för sällskap.
        /// </summary>
        internal static string MenuRad4 {
            get {
                return ResourceManager.GetString("MenuRad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 = Upprepa tio gånger.
        /// </summary>
        internal static string MenuRad5 {
            get {
                return ResourceManager.GetString("MenuRad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 = Det tredje ordet.
        /// </summary>
        internal static string MenuRad6 {
            get {
                return ResourceManager.GetString("MenuRad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välkommen till huvud menyn!.
        /// </summary>
        internal static string MenuRubrik {
            get {
                return ResourceManager.GetString("MenuRubrik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt val: .
        /// </summary>
        internal static string MenuVal {
            get {
                return ResourceManager.GetString("MenuVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltig ålder..
        /// </summary>
        internal static string OgiltigAlder {
            get {
                return ResourceManager.GetString("OgiltigAlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt antal personer..
        /// </summary>
        internal static string OgiltigtAntalPersoner {
            get {
                return ResourceManager.GetString("OgiltigtAntalPersoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pensionärspris: 90kr.
        /// </summary>
        internal static string Pensionarspris {
            get {
                return ResourceManager.GetString("Pensionarspris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmet avslutas..
        /// </summary>
        internal static string ProgrammetAvslutas {
            get {
                return ResourceManager.GetString("ProgrammetAvslutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardpris: 120kr.
        /// </summary>
        internal static string Standardpris {
            get {
                return ResourceManager.GetString("Standardpris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalkostnad: .
        /// </summary>
        internal static string Totalkostnad {
            get {
                return ResourceManager.GetString("Totalkostnad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungdomspris: 80kr.
        /// </summary>
        internal static string Ungdomspris {
            get {
                return ResourceManager.GetString("Ungdomspris", resourceCulture);
            }
        }
    }
}
