name: Build DocFX and publish Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build Exercise1 docs
        run: docfx Exercise1/Exercise1/docs/docfx.json

      - name: Build Exercise2 docs
        run: docfx Exercise2/Exercise2/docs/docfx.json

      - name: Prepare combined site
        run: |
          mkdir -p combined_site/Exercise1
          mkdir -p combined_site/Exercise2

          cp -r Exercise1/Exercise1/docs/_site/* combined_site/Exercise1/
          cp -r Exercise2/Exercise2/docs/_site/* combined_site/Exercise2/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: combined_site

      - name: Debug paths
        run: |
          pwd
          ls -R

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
